export interface IGlobal {
  p?:string,
  pt?: string,
  pb?: string,
  pl?: string,
  pr?: string,
  m?:string,
  mt?: string,
  mb?: string,
  ml?: string,
  mr?: string,
  bg?: string,
  color?: string,
  sx?: string,
}